---
- name: get binary
  shell: curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
- name: make executable
  file:
    path: /usr/local/bin/docker-compose
    mode: +rx